apiVersion: v1
kind: Secret
metadata:
  name: k8s-app-secret  # Referenced by name in Deployments and pods
  namespace: prod
type: Opaque             # Generic secret type — free-form key-value pairs
stringData:
  DB_PASSWORD: "321123"
  DB_USER: "bokoness"
  DB_NAME: "hyperguest_dev"